include $(THEOS)/makefiles/common.mk

TOOL_NAME = suer

$(TOOL_NAME)_FILES = suer.m
$(TOOL_NAME)_CFLAGS = -fobjc-arc
$(TOOL_NAME)_CODESIGN_FLAGS = -S../entitlements.xml

include $(THEOS_MAKE_PATH)/tool.mk
